---
title: '例外: invalidArg 関数'
description: F# 'invalidArg' 関数によって引数の例外が生成される方法について説明します。
ms.date: 05/16/2016
ms.openlocfilehash: 6b1c5fdb5a541da336977d3a67d471302edb36b6
ms.sourcegitcommit: a2d0e1f66367367065bc8dc0dde488ab536da73f
ms.translationtype: HT
ms.contentlocale: ja-JP
ms.lasthandoff: 09/18/2019
ms.locfileid: "71083011"
---
# <a name="exceptions-the-invalidarg-function"></a><span data-ttu-id="e16ab-103">例外: invalidArg 関数</span><span class="sxs-lookup"><span data-stu-id="e16ab-103">Exceptions: The invalidArg Function</span></span>

<span data-ttu-id="e16ab-104">`invalidArg` 関数では、引数の例外を生成します。</span><span class="sxs-lookup"><span data-stu-id="e16ab-104">The `invalidArg` function generates an argument exception.</span></span>

## <a name="syntax"></a><span data-ttu-id="e16ab-105">構文</span><span class="sxs-lookup"><span data-stu-id="e16ab-105">Syntax</span></span>

```fsharp
invalidArg parameter-name error-message-string
```

## <a name="remarks"></a><span data-ttu-id="e16ab-106">解説</span><span class="sxs-lookup"><span data-stu-id="e16ab-106">Remarks</span></span>

<span data-ttu-id="e16ab-107">前の構文のパラメーター名は、引数が無効であるパラメーターの名前を持つ文字列です。</span><span class="sxs-lookup"><span data-stu-id="e16ab-107">The parameter-name in the previous syntax is a string with the name of the parameter whose argument was invalid.</span></span> <span data-ttu-id="e16ab-108">*error-message-string* は、リテラル文字列であるか、型 `string` の値です。</span><span class="sxs-lookup"><span data-stu-id="e16ab-108">The *error-message-string* is a literal string or a value of type `string`.</span></span> <span data-ttu-id="e16ab-109">これは、例外オブジェクトの `Message` プロパティになります。</span><span class="sxs-lookup"><span data-stu-id="e16ab-109">It becomes the `Message` property of the exception object.</span></span>

<span data-ttu-id="e16ab-110">`invalidArg` によって生成される例外は `System.ArgumentException` 例外です。</span><span class="sxs-lookup"><span data-stu-id="e16ab-110">The exception generated by `invalidArg` is a `System.ArgumentException` exception.</span></span> <span data-ttu-id="e16ab-111">次のコードは、例外をスローするための `invalidArg` の使用例を示しています。</span><span class="sxs-lookup"><span data-stu-id="e16ab-111">The following code illustrates the use of `invalidArg` to throw an exception.</span></span>

[!code-fsharp[Main](~/samples/snippets/fsharp/lang-ref-2/snippet6101.fs)]

<span data-ttu-id="e16ab-112">出力は次のようになり、その後にスタック トレースが続きます (ここには示しません)。</span><span class="sxs-lookup"><span data-stu-id="e16ab-112">The output is the following, followed by a stack trace (not shown).</span></span>

```console
December
January
System.ArgumentException: Month parameter out of range.
```

## <a name="see-also"></a><span data-ttu-id="e16ab-113">関連項目</span><span class="sxs-lookup"><span data-stu-id="e16ab-113">See also</span></span>

- [<span data-ttu-id="e16ab-114">例外処理</span><span class="sxs-lookup"><span data-stu-id="e16ab-114">Exception Handling</span></span>](index.md)
- [<span data-ttu-id="e16ab-115">例外の種類</span><span class="sxs-lookup"><span data-stu-id="e16ab-115">Exception Types</span></span>](exception-types.md)
- [<span data-ttu-id="e16ab-116">例外: `try...with` 式</span><span class="sxs-lookup"><span data-stu-id="e16ab-116">Exceptions: The `try...with` Expression</span></span>](the-try-with-expression.md)
- [<span data-ttu-id="e16ab-117">例外: `try...finally` 式</span><span class="sxs-lookup"><span data-stu-id="e16ab-117">Exceptions: The `try...finally` Expression</span></span>](the-try-finally-expression.md)
- [<span data-ttu-id="e16ab-118">例外: `raise` 関数</span><span class="sxs-lookup"><span data-stu-id="e16ab-118">Exceptions: the `raise` Function</span></span>](the-raise-function.md)
- [<span data-ttu-id="e16ab-119">例外: `failwith` 関数</span><span class="sxs-lookup"><span data-stu-id="e16ab-119">Exceptions: The `failwith` Function</span></span>](the-failwith-function.md)
