---
title: '例外: failwith 関数'
description: "'failwith' 関数で F# 例外が生成される方法について説明します。"
ms.date: 05/16/2016
ms.openlocfilehash: f2c86362d5bdde7bab55751f019965a5f4ca6236
ms.sourcegitcommit: f20dd18dbcf2275513281f5d9ad7ece6a62644b4
ms.translationtype: HT
ms.contentlocale: ja-JP
ms.lasthandoff: 07/30/2019
ms.locfileid: "68630324"
---
# <a name="exceptions-the-failwith-function"></a><span data-ttu-id="b7387-103">例外: failwith 関数</span><span class="sxs-lookup"><span data-stu-id="b7387-103">Exceptions: The failwith Function</span></span>

<span data-ttu-id="b7387-104">`failwith` 関数で F# 例外が生成されます。</span><span class="sxs-lookup"><span data-stu-id="b7387-104">The `failwith` function generates an F# exception.</span></span>

## <a name="syntax"></a><span data-ttu-id="b7387-105">構文</span><span class="sxs-lookup"><span data-stu-id="b7387-105">Syntax</span></span>

```fsharp
failwith error-message-string
```

## <a name="remarks"></a><span data-ttu-id="b7387-106">解説</span><span class="sxs-lookup"><span data-stu-id="b7387-106">Remarks</span></span>

<span data-ttu-id="b7387-107">前の構文の *error-message-string* は、リテラル文字列または型 `string` の値です。</span><span class="sxs-lookup"><span data-stu-id="b7387-107">The *error-message-string* in the previous syntax is a literal string or a value of type `string`.</span></span> <span data-ttu-id="b7387-108">これは、例外の `Message` プロパティになります。</span><span class="sxs-lookup"><span data-stu-id="b7387-108">It becomes the `Message` property of the exception.</span></span>

<span data-ttu-id="b7387-109">`failwith` によって生成される例外は `System.Exception` 例外です。これは、F# コードで名前が `Failure` の参照です。</span><span class="sxs-lookup"><span data-stu-id="b7387-109">The exception that is generated by `failwith` is a `System.Exception` exception, which is a reference that has the name `Failure` in F# code.</span></span> <span data-ttu-id="b7387-110">次のコードは、例外をスローするための `failwith` の使用例を示しています。</span><span class="sxs-lookup"><span data-stu-id="b7387-110">The following code illustrates the use of `failwith` to throw an exception.</span></span>

[!code-fsharp[Main](~/samples/snippets/fsharp/lang-ref-2/snippet6001.fs)]

## <a name="see-also"></a><span data-ttu-id="b7387-111">関連項目</span><span class="sxs-lookup"><span data-stu-id="b7387-111">See also</span></span>

- [<span data-ttu-id="b7387-112">例外処理</span><span class="sxs-lookup"><span data-stu-id="b7387-112">Exception Handling</span></span>](index.md)
- [<span data-ttu-id="b7387-113">例外の種類</span><span class="sxs-lookup"><span data-stu-id="b7387-113">Exception Types</span></span>](exception-types.md)
- [<span data-ttu-id="b7387-114">例外: `try...with` 式</span><span class="sxs-lookup"><span data-stu-id="b7387-114">Exceptions: The `try...with` Expression</span></span>](the-try-with-expression.md)
- [<span data-ttu-id="b7387-115">例外: `try...finally` 式</span><span class="sxs-lookup"><span data-stu-id="b7387-115">Exceptions: The `try...finally` Expression</span></span>](the-try-finally-expression.md)
- [<span data-ttu-id="b7387-116">例外: `raise` 関数</span><span class="sxs-lookup"><span data-stu-id="b7387-116">Exceptions: the `raise` Function</span></span>](the-raise-function.md)
